// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Keyless]
public partial class AdjustMainItemListView
{
    [StringLength(100)]
    public string MainId { get; set; } = null!;

    /// <summary>
    /// 該單據所屬的公司ID
    /// </summary>
    [StringLength(100)]
    public string CompId { get; set; } = null!;

    /// <summary>
    /// 如果單據屬於調撥單，則填入被調撥的公司ID。
    /// 非調撥單，保持空值
    /// </summary>
    [StringLength(100)]
    public string? AdjustCompId { get; set; }

    /// <summary>
    /// SHIFT : 調撥
    /// ADJUST : 盤點調整
    /// RETURN : 退庫
    /// RETURN_OUT : 退貨
    /// </summary>
    [StringLength(45)]
    public string Type { get; set; } = null!;

    /// <summary>
    /// 此單據的建立者
    /// </summary>
    [StringLength(100)]
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 目前狀態
    /// APPLY : 申請中
    /// AGREE : 同意
    /// REJECT : 拒絕
    /// CLOSE : 結案
    /// </summary>
    [StringLength(45)]
    public string CurrentStatus { get; set; } = null!;

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }

    [StringLength(100)]
    public string AdjustItemId { get; set; } = null!;

    [StringLength(100)]
    public string ProductId { get; set; } = null!;

    [StringLength(200)]
    public string ProductCode { get; set; } = null!;

    public float BeforeQuantity { get; set; }

    public float AfterQuantity { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? ItemCreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? ItemUpdatedAt { get; set; }
}