// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 公告更改紀錄
/// </summary>
[Table("announcement_history")]
public partial class AnnouncementHistory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(1000)]
    public string OldTitle { get; set; }

    [StringLength(1000)]
    public string NewTitle { get; set; }

    [StringLength(1000)]
    public string OldContent { get; set; }

    [StringLength(2000)]
    public string NewContent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OldBeginPublishTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NewBeginPublishTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OldEndPublishTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NewEndPublishTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OldBeginViewTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NewBeginViewTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OldEndViewTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NewEndViewTime { get; set; }

    public bool? OldIsActive { get; set; }

    public bool? NewIsActive { get; set; }

    [Required]
    [Column("AnnounceID")]
    [StringLength(100)]
    public string AnnounceId { get; set; }

    [Required]
    [Column("CreatorID")]
    [StringLength(100)]
    public string CreatorId { get; set; }

    [StringLength(100)]
    public string CreatorName { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedTime { get; set; }

    [Column("OldAttID")]
    [StringLength(100)]
    public string OldAttId { get; set; }

    [Column("NewAttID")]
    [StringLength(100)]
    public string NewAttId { get; set; }

    [StringLength(2000)]
    public string OldReaderUserIdList { get; set; }

    [StringLength(2000)]
    public string NewReaderUserIdList { get; set; }

    [Required]
    [StringLength(45)]
    public string Action { get; set; }
}