// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 系統先行設定申請的審核流程
/// </summary>
[PrimaryKey("SettingId", "CompId")]
[Table("apply_product_flow_setting")]
public partial class ApplyProductFlowSetting
{
    [Key]
    [StringLength(100)]
    public string SettingId { get; set; }

    /// <summary>
    /// 所屬組織ID
    /// </summary>
    [Key]
    [StringLength(100)]
    public string CompId { get; set; }

    /// <summary>
    /// 審核流程顯示名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string FlowName { get; set; }

    /// <summary>
    /// 順序
    /// </summary>
    public int Sequence { get; set; }

    /// <summary>
    /// 此審核流程的審核者
    /// </summary>
    [Required]
    [StringLength(100)]
    public string UserId { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }
}