// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 權限階層 Table
/// </summary>
[Table("authlayer")]
[Index("AuthName", Name = "AuthName_UNIQUE", IsUnique = true)]
[Index("AuthValue", Name = "AuthValue_UNIQUE", IsUnique = true)]
public partial class Authlayer
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(45)]
    public string AuthName { get; set; }

    public short? AuthValue { get; set; }

    public bool IsCreateAnnouce { get; set; }

    public bool IsUpdateAnnouce { get; set; }

    public bool IsDeleteAnnouce { get; set; }

    public bool IsHideAnnouce { get; set; }

    public bool IsCreateHandover { get; set; }

    public bool IsUpdateHandover { get; set; }

    public bool IsDeleteHandover { get; set; }

    public bool IsMemberControl { get; set; }

    public bool IsCheckReport { get; set; }

    [StringLength(100)]
    public string AuthDescription { get; set; }
}