// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// Company 規範目前庫存系統內的組織，透過 Type 欄位來區分組織是屬於一般組織，或是系統擁有者（廠商），廠商可以具有權限查閱所有機構的庫存資料。
/// </summary>
[Table("company")]
public partial class Company
{
    /// <summary>
    /// PK, 公司ID
    /// </summary>
    [Key]
    [StringLength(100)]
    public string CompId { get; set; }

    /// <summary>
    /// 顯示名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 是否激活狀態
    /// </summary>
    [Required]
    public bool? IsActive { get; set; }

    /// <summary>
    /// 類型
    /// OWNER : 系統擁有者（廠商）
    /// ORGANIZATION : 機構（醫院）
    /// </summary>
    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }
}