// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 丟棄紀錄
/// </summary>
[Table("discard_records")]
[Index("OutStockId", "CompId", Name = "compId_outStockId_idx")]
public partial class DiscardRecord
{
    [Key]
    [StringLength(100)]
    public string DiscardId { get; set; } = null!;

    [StringLength(100)]
    public string? CompId { get; set; }

    [StringLength(100)]
    public string OutStockId { get; set; } = null!;

    public float? OutStockQuantity { get; set; }

    public float ApplyQuantity { get; set; }

    /// <summary>
    /// 出庫時間(開封時間)
    /// </summary>
    [Column(TypeName = "timestamp")]
    public DateTime OutStockTime { get; set; }

    [StringLength(100)]
    public string ProductId { get; set; } = null!;

    [StringLength(200)]
    public string ProductCode { get; set; } = null!;

    [StringLength(200)]
    public string ProductName { get; set; } = null!;

    [StringLength(300)]
    public string? ProductSpec { get; set; }

    [StringLength(100)]
    public string? LotNumber { get; set; }

    [StringLength(100)]
    public string? LotNumberBatch { get; set; }

    [StringLength(100)]
    public string DiscardUserId { get; set; } = null!;

    [StringLength(100)]
    public string DiscardUserName { get; set; } = null!;

    [StringLength(100)]
    public string OutStockUserId { get; set; } = null!;

    [StringLength(100)]
    public string OutStockUserName { get; set; } = null!;

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }

    [StringLength(300)]
    public string? DiscardReason { get; set; }
}