// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("email_notify_members")]
public partial class EmailNotifyMember
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(100)]
    public string? UserId { get; set; }

    /// <summary>
    /// EXPIRED,NOT_ENOUGH
    /// </summary>
    [StringLength(45)]
    public string? NotifyType { get; set; }

    [StringLength(100)]
    public string CompId { get; set; } = null!;
}