// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("handover_detail_history")]
public partial class HandoverDetailHistory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string HandoverDetailId { get; set; }

    [StringLength(1000)]
    public string OldTitle { get; set; }

    [StringLength(1000)]
    public string NewTitle { get; set; }

    [StringLength(2000)]
    public string OldContent { get; set; }

    [StringLength(2000)]
    public string NewContent { get; set; }

    [Column("MainSheetID")]
    public int MainSheetId { get; set; }

    [Column(TypeName = "json")]
    public string OldJsonContent { get; set; }

    [Column(TypeName = "json")]
    public string NewJsonContent { get; set; }

    [StringLength(45)]
    public string CreatorId { get; set; }

    [StringLength(45)]
    public string CreatorName { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(1000)]
    public string OldReaderUserIds { get; set; }

    [StringLength(1000)]
    public string NewReaderUserIds { get; set; }

    [StringLength(2000)]
    public string OldReaderUserNames { get; set; }

    [StringLength(2000)]
    public string NewReaderUserNames { get; set; }

    [Column(TypeName = "text")]
    public string OldFileAttIds { get; set; }

    [Column(TypeName = "text")]
    public string NewFileAttIds { get; set; }

    [Required]
    [StringLength(45)]
    public string Action { get; set; }
}