// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("handover_detail_readers")]
public partial class HandoverDetailReader
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string HandoverDetailId { get; set; }

    [Required]
    [StringLength(45)]
    public string UserId { get; set; }

    [Required]
    [StringLength(45)]
    public string UserName { get; set; }

    public bool IsRead { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? ReadTime { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedTime { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedTime { get; set; }
}