// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("handover_detail")]
public partial class HandoverDetail
{
    [Key]
    [StringLength(100)]
    public string HandoverDetailId { get; set; }

    [StringLength(1000)]
    public string Title { get; set; }

    [StringLength(2000)]
    public string Content { get; set; }

    [Column("MainSheetID")]
    public int MainSheetId { get; set; }

    [Column(TypeName = "json")]
    public string JsonContent { get; set; }

    [StringLength(45)]
    public string CreatorId { get; set; }

    [StringLength(100)]
    public string CreatorName { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedTime { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedTime { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [Column(TypeName = "text")]
    public string FileAttIds { get; set; }
}