// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 交班表主表底下組別
/// </summary>
[Table("handover_sheet_group")]
[Index("SheetGroupId", Name = "SheetGroupID_UNIQUE", IsUnique = true)]
public partial class HandoverSheetGroup
{
    [Key]
    [Column("id")]
    [StringLength(100)]
    public string Id { get; set; }

    /// <summary>
    /// handover_sheet_main.SheetID
    /// </summary>
    [Column("MainSheetID")]
    public int? MainSheetId { get; set; }

    /// <summary>
    /// GUID
    /// </summary>
    [Column("SheetGroupID")]
    public int SheetGroupId { get; set; }

    [StringLength(100)]
    public string GroupTitle { get; set; }

    [StringLength(200)]
    public string GroupDescription { get; set; }

    public int GroupRank { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [StringLength(100)]
    public string CreatorName { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedTime { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedTime { get; set; }
}