// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 交班表組別底下的Row資料
/// </summary>
[Table("handover_sheet_row")]
[Index("SheetRowId", Name = "SheetRowID_UNIQUE", IsUnique = true)]
public partial class HandoverSheetRow
{
    [Key]
    [Column("id")]
    [StringLength(100)]
    public string Id { get; set; }

    /// <summary>
    /// handover_sheet_main.SheetID
    /// </summary>
    [Column("MainSheetID")]
    public int? MainSheetId { get; set; }

    /// <summary>
    /// handover_sheet_group.SheetGroupID
    /// </summary>
    [Column("SheetGroupID")]
    public int? SheetGroupId { get; set; }

    [Column("SheetRowID")]
    public int SheetRowId { get; set; }

    /// <summary>
    /// 星期幾要做這個項目
    /// </summary>
    [StringLength(100)]
    public string WeekDays { get; set; }

    [StringLength(100)]
    public string SheetGroupTitle { get; set; }

    [StringLength(45)]
    public string RowCategory { get; set; }

    [StringLength(100)]
    public string MachineBrand { get; set; }

    [StringLength(100)]
    public string MachineCode { get; set; }

    [StringLength(200)]
    public string MachineSpec { get; set; }

    [StringLength(100)]
    public string MaintainItemName { get; set; }

    [StringLength(200)]
    public string MaintainItemDescription { get; set; }

    [StringLength(100)]
    public string MaintainItemType { get; set; }

    [StringLength(100)]
    public string MaintainAnswerType { get; set; }

    [StringLength(1000)]
    public string Remarks { get; set; }

    [StringLength(100)]
    public string CreatorName { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedTime { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedTime { get; set; }
}