// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("instrument")]
public partial class Instrument
{
    [Key]
    public int InstrumentId { get; set; }

    [StringLength(100)]
    public string CompId { get; set; } = null!;

    [StringLength(100)]
    public string InstrumentName { get; set; } = null!;

    [Required]
    public bool? IsActive { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }

    [StringLength(100)]
    public string CreateUserId { get; set; } = null!;

    [StringLength(100)]
    public string? CreateUserName { get; set; }
}