// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("inventory_adjust_item")]
public partial class InventoryAdjustItem
{
    [Key]
    [StringLength(100)]
    public string AdjustItemId { get; set; } = null!;

    [StringLength(100)]
    public string MainId { get; set; } = null!;

    [StringLength(100)]
    public string ProductId { get; set; } = null!;

    [StringLength(200)]
    public string ProductCode { get; set; } = null!;

    [StringLength(100)]
    public string CompId { get; set; } = null!;

    public float BeforeQuantity { get; set; }

    public float AfterQuantity { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }
}