// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 盤點及調撥處理主要單據
/// 每一筆要更新庫存紀錄（增加）的操作，都需要寫入一筆記錄在 InStockRecord，包含採購驗收、調撥、盤點（盤盈）、退庫，類型寫在 Type 欄位。
/// </summary>
[Table("inventory_adjust_main")]
public partial class InventoryAdjustMain
{
    [Key]
    public int InventoryId { get; set; }

    /// <summary>
    /// 該單據所屬的公司ID
    /// </summary>
    [Required]
    [StringLength(100)]
    public string CompId { get; set; }

    /// <summary>
    /// 如果單據屬於調撥單，則填入被調撥的公司ID。
    /// 非調撥單，保持空值
    /// </summary>
    [StringLength(100)]
    public string AdjustCompId { get; set; }

    /// <summary>
    /// SHIFT : 調撥
    /// ADJUST : 盤點調整
    /// RETURN : 退庫
    /// RETURN_OUT : 退貨
    /// </summary>
    [Required]
    [StringLength(45)]
    public string Type { get; set; }

    /// <summary>
    /// 此單據的建立者
    /// </summary>
    [Required]
    [StringLength(100)]
    public string UserId { get; set; }

    /// <summary>
    /// 目前狀態
    /// APPLY : 申請中
    /// AGREE : 同意
    /// REJECT : 拒絕
    /// CLOSE : 結案
    /// </summary>
    [Required]
    [StringLength(45)]
    public string CurrentStatus { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }
}