// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// Manufacturer 這一個表格主要是用來記錄「庫存品項的製造商」，建立此清單後，當使用者在新增庫存品項時就可直接自動下拉選擇。
/// </summary>
[Table("manufacturer")]
[Index("Code", Name = "Code_UNIQUE", IsUnique = true)]
public partial class Manufacturer
{
    [Key]
    [StringLength(100)]
    public string Id { get; set; } = null!;

    /// <summary>
    /// 製造商編號
    /// </summary>
    [StringLength(100)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 製造商名稱
    /// </summary>
    [StringLength(100)]
    public string? Name { get; set; }

    /// <summary>
    /// 備註訊息
    /// </summary>
    [StringLength(100)]
    public string? Remark { get; set; }

    /// <summary>
    /// 是否激活狀態
    /// </summary>
    [Required]
    public bool? IsActive { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }
}