// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 出庫對應入庫,可能是多對多
/// </summary>
[Table("outstock_relateto_instock")]
public partial class OutstockRelatetoInstock
{
    [Key]
    [StringLength(100)]
    public string OutStockId { get; set; } = null!;

    [StringLength(100)]
    public string? InStockId { get; set; }

    [StringLength(100)]
    public string? LotNumberBatch { get; set; }

    [StringLength(100)]
    public string? LotNumber { get; set; }

    public float? Quantity { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }
}