// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("product_instruments")]
[Index("ProductId", "InstrumentId", Name = "unique_product_instrument", IsUnique = true)]
public partial class ProductInstrument
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string? ProductId { get; set; }

    public int? InstrumentId { get; set; }
}