// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 紀錄sub_item被更改或刪除的紀錄
/// </summary>
[Table("purchase_sub_item_history")]
public partial class PurchaseSubItemHistory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// ADD,MODIFY,DELETE
    /// </summary>
    [StringLength(45)]
    public string Action { get; set; } = null!;

    [StringLength(100)]
    public string ItemId { get; set; } = null!;

    [StringLength(100)]
    public string PurchaseMainId { get; set; } = null!;

    [StringLength(100)]
    public string PurchaseOrderNo { get; set; } = null!;

    [Column(TypeName = "json")]
    public string? BeforeValues { get; set; }

    [Column(TypeName = "json")]
    public string? AfterValues { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }

    [StringLength(100)]
    public string UserId { get; set; } = null!;

    [StringLength(100)]
    public string UserName { get; set; } = null!;
}