// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 品項的採購單據列表
/// </summary>
[Table("purchase_sub_item")]
public partial class PurchaseSubItem
{
    [Key]
    [StringLength(100)]
    public string ItemId { get; set; } = null!;

    /// <summary>
    /// 品項備註內容
    /// </summary>
    [StringLength(300)]
    public string? Comment { get; set; }

    /// <summary>
    /// 所屬組織ID
    /// </summary>
    [StringLength(100)]
    public string CompId { get; set; } = null!;

    /// <summary>
    /// 品項的PK，
    /// 參考 Product Table
    /// </summary>
    [StringLength(100)]
    public string ProductId { get; set; } = null!;

    [StringLength(200)]
    public string? ProductCode { get; set; }

    /// <summary>
    /// 品項名稱
    /// </summary>
    [StringLength(200)]
    public string ProductName { get; set; } = null!;

    /// <summary>
    /// 品項規格
    /// </summary>
    [StringLength(300)]
    public string ProductSpec { get; set; } = null!;

    [Column("UDISerialCode")]
    [StringLength(300)]
    public string? UdiserialCode { get; set; }

    /// <summary>
    /// PurchaseMainSheet PK
    /// </summary>
    [StringLength(100)]
    public string PurchaseMainId { get; set; } = null!;

    /// <summary>
    /// 數量
    /// </summary>
    public float? Quantity { get; set; }

    /// <summary>
    /// 已收到的數量
    /// </summary>
    public float? ReceiveQuantity { get; set; }

    /// <summary>
    /// 送單到金萬林後，目前狀態\\\\nNONE : 尚未收到結果\\\\nPART : 部分驗收入庫\\\\nDONE : 全部驗收入庫\\\\nCLOSE:金萬林不同意拆單後的採購項目\n
    /// </summary>
    [StringLength(45)]
    public string ReceiveStatus { get; set; } = null!;

    /// <summary>
    /// 品項可以設定組別ID\n在醫院端可以依照組別拆單顯示
    /// </summary>
    [StringLength(2000)]
    public string? GroupIds { get; set; }

    [StringLength(2000)]
    public string? GroupNames { get; set; }

    /// <summary>
    /// 品項的 ProductCategory, 用來醫院拆單用
    /// </summary>
    [StringLength(45)]
    public string? ProductCategory { get; set; }

    /// <summary>
    /// 這部分是由得標廠商（金萬林），在收到這張單子的品項後，可以指派該品項的供應商，再進行拆單
    /// </summary>
    public int? ArrangeSupplierId { get; set; }

    /// <summary>
    /// 這部分是由得標廠商（金萬林），在收到這張單子的品項後，可以指派該品項的供應商，再進行拆單
    /// </summary>
    [StringLength(100)]
    public string? ArrangeSupplierName { get; set; }

    /// <summary>
    /// 採購單項目在建立當下的庫存數量
    /// </summary>
    public float? CurrentInStockQuantity { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Owner從拆單建立就會帶這個參數,表示從WithCompId的採購單拆單出來的
    /// </summary>
    [StringLength(100)]
    public string? WithCompId { get; set; }

    /// <summary>
    /// Owner從拆單建立就會帶這個參數,對應對WithCompId的採購單purchase_main_sheet.PurchaseMainId
    /// </summary>
    [Column("withPurchaseMainId")]
    [StringLength(100)]
    public string? WithPurchaseMainId { get; set; }

    /// <summary>
    /// Owner從拆單建立就會帶這個參數,對應對WithCompId的purchase_sub_item.ItemId
    /// </summary>
    [Column("withItemId")]
    [StringLength(100)]
    public string? WithItemId { get; set; }

    /// <summary>
    /// NONE(表示OWNER尚未拆單過), DONE(表示OWNER已經拆單過)
    /// 
    /// </summary>
    [StringLength(45)]
    public string? SplitProcess { get; set; }

    [StringLength(45)]
    public string? OwnerProcess { get; set; }

    public float? InStockQuantity { get; set; }

    [StringLength(300)]
    public string? OwnerComment { get; set; }
}