// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 品項的採購單據列表
/// </summary>
[Table("purchase_sub_item")]
public partial class PurchaseSubItem
{
    [Key]
    [StringLength(100)]
    public string ItemId { get; set; }

    /// <summary>
    /// 品項備註內容
    /// </summary>
    [StringLength(300)]
    public string Comment { get; set; }

    /// <summary>
    /// 所屬組織ID
    /// </summary>
    [Required]
    [StringLength(100)]
    public string CompId { get; set; }

    /// <summary>
    /// 品項的PK，
    /// 參考 Product Table
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ProductId { get; set; }

    /// <summary>
    /// 品項名稱
    /// </summary>
    [Required]
    [StringLength(200)]
    public string ProductName { get; set; }

    /// <summary>
    /// 品項規格
    /// </summary>
    [Required]
    [StringLength(300)]
    public string ProductSpec { get; set; }

    /// <summary>
    /// PurchaseMainSheet PK
    /// </summary>
    [Required]
    [StringLength(100)]
    public string PurchaseMainId { get; set; }

    /// <summary>
    /// 數量
    /// </summary>
    public int? Quantity { get; set; }

    /// <summary>
    /// 已收到的數量
    /// </summary>
    public int? ReceiveQuantity { get; set; }

    /// <summary>
    /// 送單到金萬林後，目前狀態
    /// NONE : 尚未收到結果
    /// PART : 部分驗收入庫
    /// DONE : 全部驗收入庫
    /// </summary>
    [Required]
    [StringLength(45)]
    public string ReceiveStatus { get; set; }

    /// <summary>
    /// 品項可以設定組別ID
    /// 在醫院端可以依照組別拆單顯示
    /// </summary>
    [Column(TypeName = "json")]
    public string GroupId { get; set; }

    [Column(TypeName = "json")]
    public string GroupName { get; set; }

    /// <summary>
    /// 品項的 ProductCategory, 用來醫院拆單用
    /// </summary>
    [StringLength(45)]
    public string ProductCategory { get; set; }

    /// <summary>
    /// 這部分是由得標廠商（金萬林），在收到這張單子的品項後，可以指派該品項的供應商，再進行拆單
    /// </summary>
    [StringLength(100)]
    public string ArrangeSupplierId { get; set; }

    /// <summary>
    /// 這部分是由得標廠商（金萬林），在收到這張單子的品項後，可以指派該品項的供應商，再進行拆單
    /// </summary>
    [StringLength(100)]
    public string ArrangeSupplierName { get; set; }

    /// <summary>
    /// 採購單項目在建立當下的庫存數量
    /// </summary>
    public int? CurrentInStockQuantity { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }
}