// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// *假設今天有人員異動，造成單據的審核流程卡住，系統會提供一個畫面給該院區管理者，管理者進入後得強制進行審核。
/// </summary>
[Table("qc_flow_log")]
public partial class QcFlowLog
{
    [Key]
    [StringLength(100)]
    public string LogId { get; set; } = null!;

    /// <summary>
    /// 申請者的來源組織ID
    /// </summary>
    [StringLength(100)]
    public string CompId { get; set; } = null!;

    /// <summary>
    /// 對應 qc_validation_main PK
    /// </summary>
    [StringLength(100)]
    public string MainId { get; set; } = null!;

    /// <summary>
    /// 操作者的UserID
    /// </summary>
    [StringLength(100)]
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 操作者名稱
    /// </summary>
    [StringLength(100)]
    public string UserName { get; set; } = null!;

    public int Sequence { get; set; }

    /// <summary>
    /// 動作
    /// NEXT : 下一步
    /// PREV : 上一步
    /// CLOSE : 結案
    /// </summary>
    [StringLength(45)]
    public string Action { get; set; } = null!;

    /// <summary>
    /// 備註內容
    /// </summary>
    [StringLength(300)]
    public string Remarks { get; set; } = null!;

    [Column(TypeName = "timestamp")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime UpdatedAt { get; set; }
}