// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("qc_validation_main")]
public partial class QcValidationMain
{
    [Key]
    [StringLength(100)]
    public string MainId { get; set; } = null!;

    [StringLength(100)]
    public string? PurchaseMainId { get; set; }

    [StringLength(1000)]
    public string? PurchaseSubItemId { get; set; }

    [StringLength(1000)]
    public string InStockId { get; set; } = null!;

    /// <summary>
    /// 對應的入庫時間
    /// </summary>
    [Column(TypeName = "timestamp")]
    public DateTime InStockTime { get; set; }

    [StringLength(100)]
    public string InStockUserId { get; set; } = null!;

    [StringLength(100)]
    public string InStockUserName { get; set; } = null!;

    [StringLength(100)]
    public string ProductId { get; set; } = null!;

    [StringLength(200)]
    public string ProductCode { get; set; } = null!;

    [StringLength(200)]
    public string ProductName { get; set; } = null!;

    [StringLength(300)]
    public string? ProductSpec { get; set; }

    [StringLength(45)]
    public string CompId { get; set; } = null!;

    [StringLength(100)]
    public string? LotNumber { get; set; }

    [StringLength(100)]
    public string? LotNumberBatch { get; set; }

    /// <summary>
    /// 驗收類型
    /// </summary>
    [StringLength(100)]
    public string? ValidationType { get; set; }

    /// <summary>
    /// 檢驗屬性
    /// </summary>
    [StringLength(100)]
    public string? ValidationMethod { get; set; }

    [StringLength(100)]
    public string? ValidationItemName { get; set; }

    /// <summary>
    /// 備註說明
    /// </summary>
    [Column(TypeName = "text")]
    public string? Comment { get; set; }

    /// <summary>
    /// LOT_NUMBER或LOT_NUMBER_BATCH
    /// </summary>
    [StringLength(45)]
    public string QcType { get; set; } = null!;

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(200)]
    public string? ProductModel { get; set; }

    /// <summary>
    /// 結果統整
    /// PASS(符合驗收條件),FAIL(未符合驗收條件,進行退貨)
    /// </summary>
    [StringLength(45)]
    public string? FinalResult { get; set; }

    /// <summary>
    /// 新批號驗收狀況
    /// EXECUTED,YES,NO
    /// </summary>
    [StringLength(45)]
    public string? NewLotNumberTestResult { get; set; }

    /// <summary>
    /// 新批號驗收紀錄對應編號或更換試劑文管登錄編號版次
    /// </summary>
    [StringLength(200)]
    public string? NewLotNumberTestDocumentId { get; set; }

    /// <summary>
    /// 此產品前一次入庫情況:條碼編號
    /// </summary>
    [StringLength(200)]
    public string? PreTestBarCode { get; set; }

    /// <summary>
    /// 此產品前一次入庫:PASS符合驗收條件,FAIL未符合驗收條件,OTHER已執行對應紀錄編號
    /// </summary>
    [StringLength(100)]
    public string? PreTestResult { get; set; }

    /// <summary>
    /// 此產品前一次入庫: 已執行對應紀錄編號
    /// </summary>
    [StringLength(100)]
    public string? PreTestId { get; set; }

    [StringLength(100)]
    public string? TestUserId { get; set; }

    [StringLength(100)]
    public string? TestUserName { get; set; }

    /// <summary>
    /// 組長
    /// </summary>
    [StringLength(100)]
    public string? TeamLeader { get; set; }
}