// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 系統先行設定申請的審核流程
/// </summary>
[PrimaryKey("SettingId", "CompId")]
[Table("qc_validation_flow_setting")]
public partial class QcValidationFlowSetting
{
    [Key]
    [StringLength(100)]
    public string SettingId { get; set; } = null!;

    /// <summary>
    /// 所屬組織ID
    /// </summary>
    [Key]
    [StringLength(100)]
    public string CompId { get; set; } = null!;

    /// <summary>
    /// 審核流程顯示名稱
    /// </summary>
    [StringLength(100)]
    public string FlowName { get; set; } = null!;

    /// <summary>
    /// 順序
    /// </summary>
    public int Sequence { get; set; }

    /// <summary>
    /// 此審核流程的審核者
    /// </summary>
    [StringLength(100)]
    public string? ReviewUserId { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 負責簽核的組別
    /// </summary>
    [StringLength(100)]
    public string? ReviewGroupId { get; set; }
}