// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("qc_validation_main")]
public partial class QcValidationMain
{
    [Key]
    [StringLength(100)]
    public string MainId { get; set; } = null!;

    [StringLength(100)]
    public string? PurchaseMainId { get; set; }

    [StringLength(1000)]
    public string? PurchaseSubItemId { get; set; }

    [StringLength(1000)]
    public string InStockId { get; set; } = null!;

    /// <summary>
    /// 對應的入庫時間
    /// </summary>
    [Column(TypeName = "timestamp")]
    public DateTime InStockTime { get; set; }

    [StringLength(100)]
    public string InStockUserId { get; set; } = null!;

    [StringLength(100)]
    public string InStockUserName { get; set; } = null!;

    [StringLength(100)]
    public string ProductId { get; set; } = null!;

    [StringLength(200)]
    public string ProductCode { get; set; } = null!;

    [StringLength(200)]
    public string ProductName { get; set; } = null!;

    [StringLength(300)]
    public string? ProductSpec { get; set; }

    [StringLength(45)]
    public string CompId { get; set; } = null!;

    [StringLength(100)]
    public string? LotNumber { get; set; }

    [StringLength(100)]
    public string? LotNumberBatch { get; set; }

    /// <summary>
    /// 驗收類型
    /// </summary>
    [StringLength(100)]
    public string? ValidationType { get; set; }

    /// <summary>
    /// 檢驗屬性
    /// </summary>
    [StringLength(100)]
    public string? ValidationMethod { get; set; }

    [StringLength(100)]
    public string? ValidationItemName { get; set; }

    /// <summary>
    /// 備註說明
    /// </summary>
    [Column(TypeName = "text")]
    public string? Comment { get; set; }

    /// <summary>
    /// LOT_NUMBER或LOT_NUMBER_BATCH
    /// </summary>
    [StringLength(45)]
    public string QcType { get; set; } = null!;
}