// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

[Table("qc_validation_detail")]
public partial class QcValidationDetail
{
    [Key]
    public int DetailId { get; set; }

    [StringLength(100)]
    public string MainId { get; set; } = null!;

    public int ItemNumber { get; set; }

    /// <summary>
    /// 新批號結果
    /// </summary>
    [StringLength(300)]
    public string? NewLotResult { get; set; }

    [StringLength(300)]
    public string? OldLotResult { get; set; }

    [StringLength(300)]
    public string? QuantityDiff { get; set; }

    [StringLength(300)]
    public string? ValidationResult { get; set; }
}