// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// Supplier 這一個表格主要是用來記錄「庫存品項的供應商」，建立此清單後，當使用者在新增庫存品項時就可直接自動下拉選擇。
/// </summary>
[Table("supplier")]
public partial class Supplier
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// 屬於庫存系統裡面的哪一個組織所有
    /// </summary>
    [StringLength(100)]
    public string CompId { get; set; } = null!;

    /// <summary>
    /// 供應商編號
    /// </summary>
    [StringLength(45)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 供應商公司電話
    /// </summary>
    [StringLength(100)]
    public string? CompanyPhone { get; set; }

    /// <summary>
    /// 供應商聯絡人
    /// </summary>
    [StringLength(100)]
    public string? ContactUser { get; set; }

    /// <summary>
    /// 供應商聯絡人電話
    /// </summary>
    [StringLength(100)]
    public string? ContactUserPhone { get; set; }

    /// <summary>
    /// 是否激活狀態
    /// </summary>
    [Required]
    public bool? IsActive { get; set; }

    /// <summary>
    /// 供應商名稱
    /// </summary>
    [StringLength(100)]
    public string? Name { get; set; }

    /// <summary>
    /// 備註訊息
    /// </summary>
    [StringLength(100)]
    public string? Remark { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }
}