// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace stock_api.Models;

/// <summary>
/// 盤點和調撥單據，如果是要入庫的話，會先寫入一筆資料到這個暫時的表，等到審核通過再複製到 InStockItemRecord.
/// </summary>
[Table("temp_in_stock_item_record")]
public partial class TempInStockItemRecord
{
    [Key]
    [StringLength(100)]
    public string InStockId { get; set; }

    /// <summary>
    /// 批次
    /// </summary>
    [Required]
    [StringLength(100)]
    public string LotNumberBatch { get; set; }

    /// <summary>
    /// 批號
    /// </summary>
    [Required]
    [StringLength(100)]
    public string LotNumber { get; set; }

    /// <summary>
    /// 所屬公司ID
    /// </summary>
    [Required]
    [StringLength(100)]
    public string CompId { get; set; }

    /// <summary>
    /// 現有庫存量
    /// </summary>
    public int OriginalQuantity { get; set; }

    /// <summary>
    /// 保存期限
    /// </summary>
    public DateOnly? ExpirationDate { get; set; }

    /// <summary>
    /// 此次入庫數量
    /// </summary>
    public int InStockQuantity { get; set; }

    /// <summary>
    /// 品項PK
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ProductId { get; set; }

    /// <summary>
    /// 品項名稱
    /// </summary>
    [Required]
    [StringLength(200)]
    public string ProductName { get; set; }

    /// <summary>
    /// 品項規格
    /// </summary>
    [Required]
    [StringLength(300)]
    public string ProductSpec { get; set; }

    /// <summary>
    /// 類型
    /// PURCHASE : 來源是採購
    /// SHIFT : 調撥
    /// ADJUST : 調整（盤盈）
    /// RETURN : 退庫
    /// </summary>
    [Required]
    [StringLength(45)]
    public string Type { get; set; }

    /// <summary>
    /// 執行入庫人員的UserID
    /// </summary>
    [Required]
    [StringLength(100)]
    public string UserId { get; set; }

    /// <summary>
    /// 執行入庫人員的UserName
    /// </summary>
    [Required]
    [StringLength(100)]
    public string UserName { get; set; }

    /// <summary>
    /// 用來判斷暫存項目是不是已經有複製過去 InStockItemRecord,(0)false: 未複製,(1)true: 已複製
    /// </summary>
    public bool IsTransfer { get; set; }

    /// <summary>
    /// 用來判斷屬於哪一張主單
    /// </summary>
    [Required]
    [Column("InventoryID")]
    [StringLength(100)]
    public string InventoryId { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? UpdatedAt { get; set; }
}