

ALTER TABLE `stock`.`warehouse_product` 
ADD COLUMN `QcType` VARCHAR(45) NULL DEFAULT 'NONE' COMMENT 'NONE,LOT_NUMBER,LOT_NUMBER_BATCH' AFTER `IsNeedAcceptProcess`;
ALTER TABLE `stock`.`in_stock_item_record` 
ADD COLUMN `QcType` VARCHAR(45) NULL DEFAULT 'NONE' COMMENT 'NONE,LOT_NUMBER,LOT_NUMBER_BATCH' AFTER `OutStockQuantity`,
ADD COLUMN `IsNeedQc` TINYINT(1) NULL DEFAULT 0 AFTER `QcType`,
ADD COLUMN `QcTestStatus` VARCHAR(45) NULL DEFAULT 'NONE' COMMENT 'NONE,FAIL,PASS' AFTER `IsNeedQc`;
